version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081  # Expose app on port 8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"  # Map host port 8081 to container port 8081
    depends_on:
      - db
    networks:
      - ecommerce_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
